# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_TOUCHSCREEN_NT36XXX) += nt36xxx-ts.o
nt36xxx-ts-y := nt36xxx.o nt36xxx_fw_update.o
nt36xxx-ts-$(CONFIG_TOUCHSCREEN_NT36XXX_EXT_PROC) += nt36xxx_ext_proc.o