# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_TOUCHSCREEN_NOVATEK_NT36523_I2C) += novatek-nt36523.o
novatek-nt36523-y := nt36xxx.o nt36xxx_fw_update.o
novatek-nt36523-$(CONFIG_TOUCHSCREEN_NOVATEK_NT36523_EXT_PROC) += nt36xxx_ext_proc.o
novatek-nt36523-$(CONFIG_TOUCHSCREEN_NOVATEK_NT36523_EXT_PROC) += nt36xxx_ext_proc.o
